---
openapi: 3.1.0
info:
  title: API DIM
  description: Fichier swagger correspondant à l'api des objets matters
  version: 1.0.0
servers:
  - url: http://{{server_ip}}:8080/
tags:
  - name: API DIM
    description: default api test
paths:
{{paths}}
          
components: {}

