---
openapi: 3.1.0
info:
  title: API DIM
  description: Fichier swagger correspondant à l'api des objets matters
  version: 1.0.0
servers:
  - url: http://{{server_ip}}:8080/
tags:
  - name: API DIM
    description: default api test
paths:
  "/test":
    get:
      produces:
        -application/json
      tags:
      - test
      summary: should display a random list of 5 number between [0-9]
      responses:
        '200':
          description: OK
{% for path in paths %}
{{path}}
{% endfor %}
          
components: {}

